apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: mysql-config
    configMap:
      name: mysql-demo-config
      items:
      - key: my.conf
        path: my.conf
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: mysql-config
      mountPath: /mydata
