apiVersion: v1
kind: Pod
metadata:
   name: my-pod-ns
   namespace: demo
   labels:
      app: myapp-2
spec:
   containers:
   - name: myapp-container
     image: busybox
     command: ['sh', '-c',  'echo Hello Kubernetes! && sleep 3600']
