apiVersion: v1
kind: Pod
metadata:
   name: my-secret-pod1
spec:
   containers:
   - name: myapp-container
     image: busybox
     command: ["/bin/bash"]
     args: ["-c", "sleep 600"]
     env:
     - name: myusername
       valueFrom:
          secretKeyRef:
            name: secret-demo
            key: username
