apiVersion: v1
kind: Pod
metadata:
   name: my-security-context-pod
spec:
   securityContext:
      runAsUser: 1002
      fsGroup: 10
   containers:
   - name: myapp-container
     image: busybox
     command: ['sh', '-c', "cat /etc/message/message.txt && sleep 600"]
     volumeMounts:
     - name: message-volume
       mountPath: /message
   volumes:
   - name: message-volume
     hostPath:
       path: /etc/message
